/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BaseForm: typeof import('./src/components/BaseForm.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseSwiper: typeof import('./src/components/BaseSwiper.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
