/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/aboutUs': RouteRecordInfo<'/aboutUs', '/aboutUs', Record<never, never>, Record<never, never>>,
    '/AccessibleFarm': RouteRecordInfo<'/AccessibleFarm', '/AccessibleFarm', Record<never, never>, Record<never, never>>,
    '/education': RouteRecordInfo<'/education', '/education', Record<never, never>, Record<never, never>>,
    '/food-safety': RouteRecordInfo<'/food-safety', '/food-safety', Record<never, never>, Record<never, never>>,
    '/market-price': RouteRecordInfo<'/market-price', '/market-price', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/tourism': RouteRecordInfo<'/tourism', '/tourism', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/aboutUs.vue': {
      routes: '/aboutUs'
      views: never
    }
    'src/pages/AccessibleFarm.vue': {
      routes: '/AccessibleFarm'
      views: never
    }
    'src/pages/education.vue': {
      routes: '/education'
      views: never
    }
    'src/pages/food-safety.vue': {
      routes: '/food-safety'
      views: never
    }
    'src/pages/market-price.vue': {
      routes: '/market-price'
      views: never
    }
    'src/pages/test.vue': {
      routes: '/test'
      views: never
    }
    'src/pages/tourism.vue': {
      routes: '/tourism'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
